# Generated by Django 4.1.13 on 2023-11-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer_id', models.IntegerField(default=0)),
                ('empresa_id', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
        ),
    ]
